* roll_dnd_mobs

We're running a massive final D&D 5e battlefield, and would like to roll the
dice! but having to roll 20d20 to determine if your army of archers hits is a
pain so here is some R code to simulate dice-rolls for large groups of mobs.

It shows you exactly what was rolled so you can still cheer on your army of
champions! (except for individual damage dice, but I don't care too much about
that).

* Run it locally
Save [[file:roll_dnd_mobs.R]] and open it in your local R session.

* Run this interactively online via binder [[https://mybinder.org/v2/gh/japhir/DnD_mobs/HEAD][https://mybinder.org/badge_logo.svg]]
1. wait for a long time for it to launch
2. Click on the RStudio button
3. In the bottom right click on ~roll_dnd_mobs.R~ to open it
4. In the top-right of the newly opened file, click Source
5. you can now enter my functions in the console (bottom left)!
   - ~roll_dice(1, 8)~ will roll 1d8
   - ~d20(advantage = TRUE)~ will roll a d20 with advantage
   - ~attack(19, +8, 2, 8, +4, AC = 15, adv = TRUE)~ will attack with 19
     archers that have a +8 bonus to hit. They are also colossus slayers so
     they roll 2d8+4 damage against an AC of 15, with advantage
